Project_adeo/src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @UniqueEntity("SKU")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @Assert\Type("string")
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Assert\NotBlank
     * @Assert\Type("integer")
     * @Assert\Positive
     * @ORM\Column(type="integer", unique=true)
     */
    private $SKU;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @Assert\NotBlank
     * @Assert\Positive
     * @ORM\Column(type="float")
     */
    private $base_price;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 100,
     *      minMessage = "Discount must be at least {{ limit }}%",
     *      maxMessage = "Discount cannot be bigger than {{ limit }}%"
     * )
     * @ORM\Column(type="integer", nullable=true)
     */
    private $individual_discount;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @Assert\NotBlank
     * @Assert\Type("string")
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @Assert\NotBlank
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $published_by;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="review_of_product")
     */
    private $reviews;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSKU(): ?int
    {
        return $this->SKU;
    }

    public function setSKU(int $SKU): self
    {
        $this->SKU = $SKU;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getBasePrice(): ?float
    {
        return $this->base_price;
    }

    public function setBasePrice(float $base_price): self
    {
        $this->base_price = $base_price;

        return $this;
    }

    public function getIndividualDiscount(): ?int
    {
        return $this->individual_discount;
    }

    public function setIndividualDiscount(?int $individual_discount): self
    {
        $this->individual_discount = $individual_discount;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishedBy(): ?Admin
    {
        return $this->published_by;
    }

    public function setPublishedBy(?Admin $published_by): self
    {
        $this->published_by = $published_by;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setReviewOfProduct($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getReviewOfProduct() === $this) {
                $review->setReviewOfProduct(null);
            }
        }

        return $this;
    }
}

Project_adeo/src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Admin;
use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('SKU', IntegerType::class)
            ->add('status', ChoiceType::class, [
                'label' => 'Status',
                'choices' => [
                    'Enabled' => true,
                    'Disabled' => false
                ]
            ])
            ->add('base_price', MoneyType::class)
            ->add('individual_discount', PercentType::class, [
                'type' => 'integer'
            ])
            ->add('description', TextareaType::class)
            ->add('image', FileType::class, [
                'mapped' => false,
                'label' => 'Upload image',
                'constraints' => [
                    new File([
                        'maxSize' => '10M',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/png',
                            'image/jpeg',
                        ],
                        'mimeTypesMessage' => 'Please upload image in .jpg, .jpeg or .png format',
                    ])
                ],
            ])
            ->add('published_by', EntityType::class, [
                'class' => Admin::class,
                'choice_label' => 'username',
                'disabled' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

Project_adeo/templates/product/_delete_form.html.twig
<form method="post"
      action="{{ path('product_delete', {'id': product.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');"
>
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

Project_adeo/templates/product/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form, {'attr': {'novalidate': 'novalidate'}}) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form, {'attr': {'novalidate': 'novalidate'}}) }}

Project_adeo/templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    <div class="container">
        {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

        <a class="btn btn-primary" href="{{ path('product_index') }}">Back to list</a>

        {{ include('product/_delete_form.html.twig') }}
    </div>
{% endblock %}

Project_adeo/templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Products{% endblock %}

{% block body %}
    <h1>List Of Products</h1>

    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>SKU</th>
                <th>Status</th>
                <th>Base price(€)</th>
                <th>Individual discount(%)</th>
                <th>Description</th>
                <th>Published by</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>
                        <img src="{{ asset('uploads/products_images/') ~ product.image }}"
                             style="width: 50px; height: 50px"
                             class="rounded mx-auto d-block"
                        >
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.SKU }}</td>
                    {% if product.status%}
                        <td>Enabled</td>
                        {% else %}
                            <td>Disabled</td>
                    {% endif %}
                    <td>{{ product.basePrice|number_format(2, '.', '') }}</td>
                    <td>{{ product.individualDiscount }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.publishedBy.username }}</td>
                    <td>
                        <a class="btn btn-primary" href="{{ path('product_edit', {'id': product.id}) }}">Edit</a>
                        {{ include('product/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a class="btn btn-primary" href="{{ path('product_new') }}">Create new</a>

        <div class="navigation d-flex justify-content-center">
            {{ knp_pagination_render(products) }}
        </div>
    </div>
{% endblock %}

Project_adeo/templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    <div class="container">
        {{ include('product/_form.html.twig') }}

        <a class="btn btn-primary" href="{{ path('product_index') }}">Back to list</a>
    </div>
{% endblock %}