Project_adeo/src/Entity/Configuration.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ConfigurationRepository")
 */
class Configuration
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Type("integer")
     * @Assert\Positive
     * @ORM\Column(type="integer")
     */
    private $tax_rate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_tax_included;

    /**
     * * @Assert\Range(
     *      min = 1,
     *      max = 100,
     *      minMessage = "Discount must be at least {{ limit }}%",
     *      maxMessage = "Discount cannot be bigger than {{ limit }}%"
     * )
     * @Assert\Type("integer")
     * @Assert\Positive
     * @ORM\Column(type="integer", nullable=true)
     */
    private $global_discount;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTaxRate(): ?int
    {
        return $this->tax_rate;
    }

    public function setTaxRate(int $tax_rate): self
    {
        $this->tax_rate = $tax_rate;

        return $this;
    }

    public function getIsTaxIncluded(): ?bool
    {
        return $this->is_tax_included;
    }

    public function setIsTaxIncluded(bool $is_tax_included): self
    {
        $this->is_tax_included = $is_tax_included;

        return $this;
    }

    public function getGlobalDiscount(): ?int
    {
        return $this->global_discount;
    }

    public function setGlobalDiscount(?int $global_discount): self
    {
        $this->global_discount = $global_discount;

        return $this;
    }
}

Project_adeo/src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @UniqueEntity("SKU")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @Assert\Type("string")
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Assert\NotBlank
     * @Assert\Type("integer")
     * @Assert\Positive
     * @ORM\Column(type="integer", unique=true)
     */
    private $SKU;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @Assert\NotBlank
     * @Assert\Positive
     * @ORM\Column(type="float")
     */
    private $base_price;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 100,
     *      minMessage = "Discount must be at least {{ limit }}%",
     *      maxMessage = "Discount cannot be bigger than {{ limit }}%"
     * )
     * @ORM\Column(type="integer", nullable=true)
     */
    private $individual_discount;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @Assert\NotBlank
     * @Assert\Type("string")
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @Assert\NotBlank
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $published_by;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="review_of_product")
     */
    private $reviews;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSKU(): ?int
    {
        return $this->SKU;
    }

    public function setSKU(int $SKU): self
    {
        $this->SKU = $SKU;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getBasePrice(): ?float
    {
        return $this->base_price;
    }

    public function setBasePrice(float $base_price): self
    {
        $this->base_price = $base_price;

        return $this;
    }

    public function getIndividualDiscount(): ?int
    {
        return $this->individual_discount;
    }

    public function setIndividualDiscount(?int $individual_discount): self
    {
        $this->individual_discount = $individual_discount;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishedBy(): ?Admin
    {
        return $this->published_by;
    }

    public function setPublishedBy(?Admin $published_by): self
    {
        $this->published_by = $published_by;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setReviewOfProduct($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getReviewOfProduct() === $this) {
                $review->setReviewOfProduct(null);
            }
        }

        return $this;
    }
}

Project_adeo/src/Entity/Review.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReviewRepository")
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reviewer_name;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @Assert\NotBlank
     * @Assert\Range(
     *      min = 1,
     *      max = 5,
     *      minMessage = "Rating must be at least {{ limit }}%",
     *      maxMessage = "Rating cannot be bigger than {{ limit }}%"
     * )
     * @ORM\Column(type="integer")
     */
    private $rating;

    /**
     * @ORM\Column(type="datetime")
     */
    private $post_time;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $review_of_product;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReviewerName(): ?string
    {
        return $this->reviewer_name;
    }

    public function setReviewerName(string $reviewer_name): self
    {
        $this->reviewer_name = $reviewer_name;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getPostTime(): ?\DateTimeInterface
    {
        return $this->post_time;
    }

    public function setPostTime(\DateTimeInterface $post_time): self
    {
        $this->post_time = $post_time;

        return $this;
    }

    public function getReviewOfProduct(): ?Product
    {
        return $this->review_of_product;
    }

    public function setReviewOfProduct(?Product $review_of_product): self
    {
        $this->review_of_product = $review_of_product;

        return $this;
    }
}

Project_adeo/src/Controller/HomePageController.php
<?php

namespace App\Controller;

use App\Entity\Configuration;
use App\Entity\Review;
use App\Form\ReviewType;
use App\Repository\ConfigurationRepository;
use PhpParser\Parser;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use phpDocumentor\Reflection\Types\This;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

class HomePageController extends AbstractController
{
    /**
     * @Route("/", name="home_page")
     */
    public function index(Request $request, ProductRepository $productRepository, ConfigurationRepository $configRepo, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $productRepository->findBy(['status' => true]),
            $request->query->getInt('page', 1), /*page number*/
            16 /*limit per page*/
        );

        return $this->render('home_page/index.html.twig', [
            'controller_name' => 'HomePageController',
            'products' => $pagination,
            'configuration' => $configRepo->findAll()[0]
        ]);
    }

    /**
     * @Route("/product/{id}", name="product_show", methods={"GET","POST"})
     */
    public function show(Product $product, Request $request, ConfigurationRepository $configRepo): Response
    {
        $review = new Review();
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $now = new \DateTime();
            $now->format('Y-m-d H:i:s');

            $review->setPostTime($now);
            $review->setReviewOfProduct($product);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($review);
            $entityManager->flush();

            return $this->redirectToRoute('product_show', [
                'id' => $product->getId()
            ]);
        }

        $reviews = $product->getReviews()->toArray();
        rsort($reviews);

        return $this->render('home_page/showProduct.html.twig', [
            'product' => $product,
            'reviews' => $reviews,
            'form' => $form->createView(),
            'configuration' => $configRepo->findAll()[0]
        ]);
    }
}

Project_adeo/templates/home_page/_reviewForm.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form, {'attr': {'novalidate': 'novalidate'}}) }}
    <button class="btn btn-primary">{{ button_label|default('Post') }}</button>
{{ form_end(form, {'attr': {'novalidate': 'novalidate'}}) }}

Project_adeo/templates/home_page/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home Page{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('../templates/css/star.css') }}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            {% for product in products %}

                {% if product.status %}
                    <div class="card mb-4" style="min-width: 200px; max-width: 250px">
                        <a href="{{ path('product_show', {'id': product.id}) }}">
                            <img class="card-img-top img-fluid"
                                 src="{{ asset('uploads/products_images/') ~ product.image }}"
                                 style="height: 200px"
                                 alt="{{ product.image }}"
                            >
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name|title }}</h5>

                            <p class="card_text" id="rating">
                                {% if product.getReviews()|length == 0 %}
                                    {% for i in 1..5 %}
                                        <i class="fa fa-star"></i>
                                    {% endfor %}
                                {% else %}

                                    {% set ratingSum = 0 %}

                                    {% for review in product.getReviews() %}
                                        {% set ratingSum = ratingSum + review.rating %}
                                    {% endfor %}

                                    {% set ratingAvg = ratingSum / product.getReviews()|length %}

                                    {% for i in 1..5 %}
                                        {% if loop.index <= ratingAvg %}
                                            <i class="fa fa-star checked"></i>
                                        {% else %}
                                            <i class="fa fa-star"></i>
                                        {% endif %}
                                    {% endfor %}

                                {%  endif %}

                                ( {{ product.getReviews()|length }} )
                            </p>

                            <p class="card-text">
                                SKU:{{ product.SKU }}
                            </p>

                            {% set tax = (product.basePrice / 100 * configuration.taxRate) %}

                            {% if configuration.isTaxIncluded %}
                                {% set productPrice = product.basePrice + tax %}
                            {% else %}
                                {% set productPrice = product.basePrice%}
                            {% endif %}

                            {% if product.individualDiscount != null or configuration.globalDiscount != null %}

                                {% if product.individualDiscount != null %}
                                    {% set discount =  (productPrice / 100 * product.individualDiscount)%}

                                    <p class="card-text" style="color: red">
                                        Discount: {{ product.individualDiscount }}%
                                    </p>

                                {% elseif  product.individualDiscount == null and configuration.globalDiscount != null%}
                                    {% set discount =  (productPrice / 100 * configuration.globalDiscount)%}

                                    <p class="card-text" style="color: red">
                                        Discount: {{ configuration.globalDiscount }}%
                                    </p>

                                {% endif %}

                                {% set priceBeforeSale = productPrice %}
                                {% set productPrice = productPrice - discount %}

                                <p class="card-text">
                                    Price:
                                    <strike>{{ priceBeforeSale|number_format(2, '.', '') }}€</strike>
                                    {{ productPrice|number_format(2, '.', '') }}€
                                    <br>
                                    {% if configuration.isTaxIncluded %}
                                        <small class="card-text" style="color: red">
                                            Tax included
                                        </small>
                                    {% else %}
                                        <small class="card-text" style="color: red">
                                            Tax not included
                                        </small>
                                        <br>
                                        <small class="card-text" style="color: red">
                                            Tax rate: {{ configuration.taxRate }}%
                                        </small>
                                    {% endif %}

                                </p>

                            {% else %}
                                <p><br></p>
                                <p class="card-text">
                                    Price: {{ productPrice|number_format(2, '.', '') }}€
                                    <br>
                                    {% if configuration.isTaxIncluded %}
                                        <small class="card-text" style="color: red">
                                            Tax included
                                        </small>
                                    {% else %}
                                        <small class="card-text" style="color: red">
                                            Tax not included
                                        </small>
                                        <br>
                                        <small class="card-text" style="color: red">
                                            Tax rate: {{ configuration.taxRate }}%
                                        </small>
                                    {% endif %}
                                </p>

                            {% endif %}

                            <a class="btn btn-primary"
                               href="{{ path('product_show', {'id': product.id}) }}">
                                Show more
                            </a>
                        </div>
                    </div>
                {% endif %}

            {% else %}
                <tr>
                    <td colspan="9">no records found</td>
                </tr>
            {% endfor %}
        </div>

        <div class="navigation d-flex justify-content-center">
            {{ knp_pagination_render(products) }}
        </div>
    </div>
{% endblock %}

Project_adeo/templates/home_page/showProduct.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ product.name|title }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('../templates/css/star.css') }}">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>{{ product.name|title }}</h1>
        <small style="font-size: 18px">Product SKU: {{ product.SKU }}</small>
        <div class="media">
            <img src="{{ asset('uploads/products_images/') ~ product.image }}"
                 class="mr-3"
                 style="width: 340px; height: 340px;"
                 alt="{{ product.name }}"
            >
            <div class="media-body">
                <h2 class="mt-0">Product description</h2>
                <p style="font-size: 18px">
                    {{ product.description }}
                </p>
            </div>
        </div>

        {% set tax = (product.basePrice / 100 * configuration.taxRate) %}

        {% if configuration.isTaxIncluded %}
            {% set productPrice = product.basePrice + tax %}
        {% else %}
            {% set productPrice = product.basePrice %}
        {% endif %}

        {% if product.individualDiscount != null or configuration.globalDiscount != null %}

            {% if product.individualDiscount != null %}

                {% set discount =  (productPrice / 100 * product.individualDiscount)%}
                {% set discountPercents = product.individualDiscount %}

            {% elseif  product.individualDiscount == null and configuration.globalDiscount != null%}

                {% set discount =  (productPrice / 100 * configuration.globalDiscount)%}
                {% set discountPercents = configuration.globalDiscount %}

            {% endif %}

            {% set priceBeforeSale = productPrice %}
            {% set productPrice = productPrice - discount %}

            <p style="color: red; font-size: 30px">
                Discount: {{ discountPercents }}%
            </p>
            <p style="font-size: 20px">
                Price:
                <strike>{{ priceBeforeSale|number_format(2, '.', '') }}€</strike>
                {{ productPrice|number_format(2, '.', '') }}€
                <br>
                {% if configuration.isTaxIncluded %}
                    <small class="card-text" style="color: red">
                        Tax included
                    </small>
                {% else %}
                    <small class="card-text" style="color: red">
                        Tax not included
                    </small>
                    <br>
                    <small class="card-text" style="color: red">
                        Tax rate: {{ configuration.taxRate }}%
                    </small>
                {% endif %}
            </p>

        {% else %}
            <p><br></p>
            <p style="font-size: 20px">
                Price: {{ productPrice|number_format(2, '.', '') }}€
                <br>
                {% if configuration.isTaxIncluded %}
                    <small class="card-text" style="color: red">
                        Tax included
                    </small>
                {% else %}
                    <small class="card-text" style="color: red">
                        Tax not included
                    </small>
                    <br>
                    <small class="card-text" style="color: red">
                        Tax rate: {{ configuration.taxRate }}%
                    </small>
                {% endif %}
            </p>
        {% endif %}

        <div class="container">
            <h2 class="text-center">Product Reviews</h2>

            {% for review in reviews %}
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <p>
                                    {% if review.reviewerName != null %}
                                        <strong>{{ review.reviewerName|title }}</strong>
                                    {% else %}
                                        <strong>Anonymous</strong>
                                    {% endif %}

                                    {% for i in 1..5 %}
                                        {% if loop.index <= review.rating %}
                                            <i class="fa fa-star checked"></i>
                                        {% else %}
                                            <i class="fa fa-star"></i>
                                        {% endif %}
                                    {% endfor %}

                                    <small class="float-right">{{ review.postTime|date("Y-m-d H:i:s") }}</small>
                                </p>
                                <div class="clearfix"></div>
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <br><br>
        <div class="container">
            {{ include('home_page/_reviewForm.html.twig') }}
        </div>

        <a class="btn btn-primary" href="{{ path('home_page') }}">Back to home page</a>
    </div>
{% endblock %}